// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqW61eappCIEb3eGgxuAee_yOnjJ5Zqsc',
    appId: '1:474402818165:web:bd9748a78de3e943b6103c',
    messagingSenderId: '474402818165',
    projectId: 'khetibridge2-8051c',
    authDomain: 'khetibridge2-8051c.firebaseapp.com',
    storageBucket: 'khetibridge2-8051c.appspot.com',
    measurementId: 'G-TEHXW2ZHXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JRwK4_cb7rGodNf4t9BaF9pdqa0XGL4',
    appId: '1:474402818165:android:d680a44acd9fb450b6103c',
    messagingSenderId: '474402818165',
    projectId: 'khetibridge2-8051c',
    storageBucket: 'khetibridge2-8051c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_QS9nPZVKR7rfz-heph8NWgT2QyBm_So',
    appId: '1:474402818165:ios:26513df824bcfe35b6103c',
    messagingSenderId: '474402818165',
    projectId: 'khetibridge2-8051c',
    storageBucket: 'khetibridge2-8051c.appspot.com',
    iosBundleId: 'com.example.khetiProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_QS9nPZVKR7rfz-heph8NWgT2QyBm_So',
    appId: '1:474402818165:ios:26513df824bcfe35b6103c',
    messagingSenderId: '474402818165',
    projectId: 'khetibridge2-8051c',
    storageBucket: 'khetibridge2-8051c.appspot.com',
    iosBundleId: 'com.example.khetiProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqW61eappCIEb3eGgxuAee_yOnjJ5Zqsc',
    appId: '1:474402818165:web:b952b74217e57ecbb6103c',
    messagingSenderId: '474402818165',
    projectId: 'khetibridge2-8051c',
    authDomain: 'khetibridge2-8051c.firebaseapp.com',
    storageBucket: 'khetibridge2-8051c.appspot.com',
    measurementId: 'G-3BHLJYVKJB',
  );

}